### ISSUE TITLE
Running Ubuntu in Synology docker

### ISSUE THREAD

**Issue by AbDhops** [tianon/docker-brew-ubuntu-core#197]
Good evening All,
I am trying to run ubuntu in docker in Synology. Below is my docker-compose.
```
version: "3"

services:
  ubuntu:
    container_name: ubuntu
    image: ubuntu:18.04
    # hostname: ubuntu
    network_mode: "host"
    volumes:
       - './opt/motion-ai/:/opt/motion-ai/'
       - './var/motion-ai-scripts/:/var/motion-ai-scripts/'
       # - './etc/passwd:/etc/passwd'
       # - './etc/shadow:/etc/shadow'
    restart: always
    command: ["sleep","infinity"]
```

Ubuntu is running, I am able to "enter" into Ubuntu.
`docker exec -it ubuntu /bin/bash`
Once loged in into ubuntu, I am able to run apt-update and install and update via apt. 
Now, I am trying to add new user "user1"

```
root@media:/# adduser --disabled-password --no-create-home --gecos "" --shell /bin/bash user1
Adding user `user1' ...
Adding new group `user1' (1000) ...
Adding new user `user1' (1000) with group `user1' ...
Not creating home directory `/home/user1'.
chfn: PAM: System error
adduser: `/usr/bin/chfn -f  user1' returned error code 1. Exiting.
```

Even after error, user is added ! (I get the error if I am trying to add it again"

Ultimately, I want to have a user (home and password doesn't matter) who can use "sudo" commands.

Any help for doing it is appreciated.

Many thanks.
